### ISSUE TITLE
Maya 2019

### ISSUE THREAD

**Issue by ChristopheMoreau** [bram0101/openVDB_mayaGUI#3]
Hi and thanks for the script!

Is it usable with Maya 2019.2 ? Actually I can't load the plugin, it works perfectly on 2018.5 but not en 2019.2 (same install like explain in the doc.)

Thanks.

**Comment by bram0101** [comment]
The plugin's code should work with Maya 2019, but the compiled plugin (the .mll file) is only compatible with Maya 2018. If you would want it to work with Maya 2019, then you would have to compile the plugin for Maya 2019.

Unfortunately, I am no longer using this script myself and I do not have the time to maintain it either. Luckily, compiling the plugin yourself is something that you can do with completely free programs. It would only take some time to figure things out. For me, compiling the OpenVDB library took the most amount of time. Maybe someone else could compile it and share it here.

In any case, I wish you good luck.
